// <auto-generated />
namespace MUESystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class billbilltype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billbilltype));
        
        string IMigrationMetadata.Id
        {
            get { return "201705050537040_bill-billtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
